const REGISTER_USER = 'REGISTER_USER';
const LOGIN_USER = 'LOGIN_USER';
const UPDATE_USER = 'UPDATE_USER';
const ADD_USER = 'ADD_USER';

type userMethods = 'REGISTER_USER' | 'LOGIN_USER' | 'UPDATE_USER' | 'ADD_USER';

export { REGISTER_USER, LOGIN_USER, UPDATE_USER, ADD_USER, userMethods };
