const REGISTER_USER = "REGISTER_USER";
const LOGIN_USER = "LOGIN_USER";
const UPDATE_USER = "UPDATE_USER";
const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
const RESET_PASSWORD = "RESET_PASSWORD";

type userMethods =
  | "REGISTER_USER"
  | "LOGIN_USER"
  | "UPDATE_USER"
  | "RESET_PASSWORD_REQUEST"
  | "RESET_PASSWORD";

export {
  REGISTER_USER,
  LOGIN_USER,
  UPDATE_USER,
  RESET_PASSWORD,
  RESET_PASSWORD_REQUEST,
  userMethods
};
