const REGISTER_USER = "REGISTER_USER";
const LOGIN_USER = "LOGIN_USER";
const UPDATE_USER = "UPDATE_USER";

type userMethods = "REGISTER_USER" | "LOGIN_USER" | "UPDATE_USER";

export { REGISTER_USER, LOGIN_USER, UPDATE_USER, userMethods };
