export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const USER_LOADED = "USER_LOADED";
export const USER_LOAD_ERROR = "USER_LOAD_ERROR";
