export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const ALERT_ADDED = "ALERT_ADDED";
export const ALERT_CLEARED = "ALERT_CLEARED";
